# Import Library

In [65]:
import os
import re
import joblib
import numpy as np
import pandas as pd

from pathlib import Path

from nltk.tokenize import word_tokenize

# Config

In [66]:
# =========================
# CONFIGURATION
# =========================

SCENARIO = 3

"""
1 : TF-IDF + Naive Bayes
2 : TF-IDF + SVM
3 : FastText + SVM
4 : IndoBERT
"""

# 0 = Full
# 1 = 10k
# 2 = 20k
# 3 = 30k
# 4 = 40k

CORPUS_SIZE = 0
CORPUS_MAP = {
    0:"full",
    1:"10k",
    2:"20k",
    3:"30k",
    4:"40k"
}
DATASET_NAME = CORPUS_MAP[CORPUS_SIZE]

print()

print("Scenario :", SCENARIO)
print("Corpus   :", DATASET_NAME)

Scenario : 3
Corpus   : full

In [67]:
CONFIG = {

    1:{
        "name":"tfidf_nb",
        "vectorizer": f"models/skenario 1/tfidf_nb_vectorizer_{DATASET_NAME}.joblib",
        "model":f"models/skenario 1/tfidf_nb_{DATASET_NAME}.joblib"
    },

    2:{

        "name":"tfidf_svm",
        "vectorizer":f"models/skenario 2/tfidf_svm_vectorizer_{DATASET_NAME}.joblib",
        "model":f"models/skenario 2/tfidf_svm_{DATASET_NAME}.joblib"
    },

    3:{
        "name":"fasttext_svm",
        "embedding":f"vectorizers/skenario 3/fasttext_{DATASET_NAME}.joblib",
        "model":f"models/skenario 3/fasttext_svm_{DATASET_NAME}.joblib"
    },

    4:{
        "name":"indobert",
        "model_dir": f"models/skenario 4/indobert_{DATASET_NAME}"
    }

}

if SCENARIO not in CONFIG:
    raise ValueError("SCENARIO tidak valid!")

print()
print(CONFIG[SCENARIO])

{'name': 'fasttext_svm', 'embedding': 'vectorizers/skenario 3/fasttext_full.joblib', 'model': 'models/skenario 3/fasttext_svm_full.joblib'}

# Load Data & Label Encoder

In [68]:
df = pd.read_csv("dataset/unseen.csv")
print()

print(df.shape)
display(df.head())

(300, 2)

                                               Tweet      Category
0       itulah yang saya rasakan tentang The Sandman  Entertaiment
1  Kompilasi video kecepatan 4x dari sesi gacha 4...  Entertaiment
2  Jadwal MPL ID S17 Week 8 Hari Ini: Dewa United...    Technology
3  SALAH SATU PENYEBAB KEMISKINAN BUKAN KARENA KE...       Economy
4  bayangkan jika setiap serial animasi meningkat...  Entertaiment

In [69]:
def preprocess_text(text):

    text = str(text).lower()

    text = re.sub(

        r"https?://\S+|www\.\S+",

        " ",

        text

    )

    text = re.sub(

        r"@\w+",

        " ",

        text

    )

    text = re.sub(

        r"#",

        "",

        text

    )

    text = re.sub(

        r"\s+",

        " ",

        text

    )

    return text.strip()

df["text_clean"] = df["Tweet"].apply(preprocess_text)

In [70]:
le = joblib.load("dataset/preprocessed/label_encoder.pkl")

print()
print("Preprocessing Completed!")

display(
    df[[
            "Category",
            "text_clean"
        ]].head()
)

Preprocessing Completed!

       Category                                         text_clean
0  Entertaiment       itulah yang saya rasakan tentang the sandman
1  Entertaiment  kompilasi video kecepatan 4x dari sesi gacha 4...
2    Technology  jadwal mpl id s17 week 8 hari ini: dewa united...
3       Economy  salah satu penyebab kemiskinan bukan karena ke...
4  Entertaiment  bayangkan jika setiap serial animasi meningkat...

# Scenario 1

In [71]:
if SCENARIO == 1:

    vectorizer = joblib.load(CONFIG[1]["vectorizer"])
    model = joblib.load(CONFIG[1]["model"])
    X = vectorizer.transform(df["text_clean"])
    pred = model.predict(X)

    print()
    print("TF-IDF + Naive Bayes Loaded!")

# Scenario 2

In [72]:
if SCENARIO == 2:

    vectorizer = joblib.load(CONFIG[2]["vectorizer"])
    model = joblib.load(CONFIG[2]["model"])
    X = vectorizer.transform(df["text_clean"])
    pred = model.predict(X)

    print()
    print("TF-IDF + SVM Loaded!")

# Scenario 3

In [73]:
def sentence_vector_fasttext(
    tokens,
    model,
    vector_size=300
):
    vectors = []
    for token in tokens:
        if token in model.wv:
            vectors.append(model.wv[token])

    if len(vectors) == 0:
        return np.zeros(vector_size)

    return np.mean(vectors, axis=0)

In [74]:
if SCENARIO == 3:

    ft_model = joblib.load(CONFIG[3]["embedding"])
    svm_model = joblib.load(CONFIG[3]["model"])
    tokens = [
        word_tokenize(text)
        for text in df["text_clean"]
    ]

    X = np.array([
        sentence_vector_fasttext(
            token,
            ft_model
        )
        for token in tokens
    ])

    pred = svm_model.predict(X)

    print()
    print("FastText + SVM Loaded!")

FastText + SVM Loaded!

# Scenario 4

In [75]:
if SCENARIO == 4:

    import torch
    from transformers import (
        AutoTokenizer,
        AutoModelForSequenceClassification
    )

    MODEL_PATH = CONFIG[4]["model_dir"]
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)
    model.eval()

    pred = []
    for text in df["text_clean"]:
        inputs = tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=128
        )

        with torch.no_grad():
            outputs = model(
                **inputs
            )

        label = torch.argmax(
            outputs.logits,
            dim=1
        )

        pred.append(label.item())

    pred = np.array(pred)

    print()
    print("IndoBERT Loaded!")

# Decode Prediction

In [76]:
df["prediction"] = le.inverse_transform(pred)
print()
print("Prediction Completed!")

display(
    df[[
        "Tweet",
        "prediction"
        ]]
)

Prediction Completed!

                                                 Tweet     prediction
0         itulah yang saya rasakan tentang The Sandman  Entertainment
1    Kompilasi video kecepatan 4x dari sesi gacha 4...  Entertainment
2    Jadwal MPL ID S17 Week 8 Hari Ini: Dewa United...        Economy
3    SALAH SATU PENYEBAB KEMISKINAN BUKAN KARENA KE...  Entertainment
4    bayangkan jika setiap serial animasi meningkat...  Entertainment
5                         Ini animasi yang luar biasa?  Entertainment
6    Tahun ini lebih dari sekadar acara tahunan bes...        Economy
7    Apple Umumkan Fitur Aksesibilitas Baru Berbasi...     Technology
8    Klarifikasi dulu fakta di balik ambruknya IHSG...  Entertainment
9    Lebih Murah! Ini Harga AirTag 2 Paket 4 Pack d...        Economy
10                               Apakah ini animenya??     Technology
11   Singapura kini melampaui pasar saham terbesar ...        Economy
12                              EP1 sub bahasa Inggris        Economy
13   Sobat  gajian belum tiba  nanti kalau gajian  ...  Entertainment
14   Cara BRIN Ramal Cuaca Dulu vs Sekarang  Bakal ...  Entertainment
15             apa hubungannya dengan gambar tersebut?  Entertainment
16   Dia melipat begitu keras sehingga seluruh fand...        Economy
17   Jujur saja gambar diam selalu terlihat lebih b...  Entertainment
18   Data Satelit Jadi Andalan Mitigasi Bencana  Te...     Technology
19    Bulan Terus Menjauh dari Bumi  Bahaya Nggak Nih?     Technology
20   Mengapa rencana Indonesia untuk mempertahankan...        Economy
21   Pria Ini Rakit Komputer Setipis Kartu Kredit  ...  Entertainment
22   Saya sangat setuju! Visualnya sungguh menakjub...     Technology
23   Ling Cage (2019) Seri Lengkap | Tonton Daring ...        Economy
24   Google Search Berubah Total Setelah 25 Tahun  ...     Technology
25   Minat investor asing terhadap Indonesia tetap ...        Economy
26   KSJDKSJDKJS Saya terhipnotis di depan adegan i...  Entertainment
27              Kami sedang membangun Pangkalan Bulan!        Economy
28   Instagram Luncurkan Fitur Instants  Apa Bedany...     Technology
29   semoga algo menghukum semua poster yang tidak ...  Entertainment
30   Keadaan ekonomi saudara ini mewakili banyak lu...  Entertainment
31   Urusan Foto Deepfake Lingerie yang Ditanggapi ...  Entertainment
32   Ayah bilang rasio utang Indonesia 40%  paling ...  Entertainment
33   Kesehatan fiskal Indonesia kuat dan aman! Ment...        Economy
34   Setiap frame tampak seperti milik layar biosko...     Technology
35   Usai Batasi Usia   Komdigi Akan Wajibkan Akun ...     Technology
36   Jika Anda ingin mengetahui keadaan perekonomia...        Economy
37   MANDIRI DI BULAN RAMADAN BAZNAS DAN AKSESMU PE...  Entertainment
38   Khususnya di Indo: â¢ Lowongan kerja menurun ...        Economy
39   HBO Max Indonesia  Disney Hotstar Indonesia  d...     Technology
40   Selamat pagi. Bangun tidur dan mendapati $1 se...  Entertainment
41   masalahnya  dosanya selama 32 tahun itu dampak...        Economy
42   Saya masih tidak percaya kami memiliki karakte...  Entertainment
43   Ingin tahu lebih detail bagaimana Pak Habibie ...  Entertainment
44   The Economist yang mengungkap belanja pemerint...        Economy
45   Punya presiden halu bikin sengsara rakyatnya g...        Economy
46                                            Namanya?     Technology
47                di mana saya bisa menonton acara ini  Entertainment
48   Perbanding iPhone 17e vs 16e: Serupa Tapi Ada ...     Technology
49   Pedang juga merupakan sinematografi yang epik ...  Entertainment
50   Talenta Digital ASEAN Bersaing Sengit di 10th ...  Entertainment
51   Banyak yang baru sadar setelah kejadian. HP le...        Economy
52                          Anda pernah ke Blackreach?  Entertainment
53   Gada!!!yg Ada indon tambah bobrok  punya tamba...        Economy
54                    Materi Kenaikan Lucy dan Rebecca  Entertainment
55   pekerjaan rumah yang paling laki-laki dilakuin...        Economy
56   mau jadi anak bos tambang yang kalo pindahan m...  Entertainment
57   Tidak Sedang Runtuh  Sedang Diuji Oleh: Abdull...        Economy
58   Supermicro baru saja meluncurkan platform serv...     Technology
59   Rupiah melemah  IHSG anjlok  dan pasar keuanga...        Economy
60                                   Platform apa itu?        Economy
61   Bank menaikkan suku bunga sebesar 50bps menjad...        Economy
62   Rupiah tembus Rp17.700. Cadangan devisa makin ...        Economy
63   Fitur Baru HP Samsung Bisa Blokir Aplikasi yan...     Technology
64   Wujud Honor X6c  HP Rp 2 Jutaan Bawa Baterai B...        Economy
65   Meski Purbaya kerap mengklaim keadaan baik-bai...        Economy
66   Pertumbuhan Indonesia tertahan di kisaran 5%. ...        Economy
67   Aduh! SEKALI LAGI SENDER MEMOHON KURO UNTUK ME...  Entertainment
68   Sejauh ini  situasi perang menunjukkan tanda-t...        Economy
69               Honor Janjikan Harga X7d Bakal Stabil        Economy
70   3 HP Ultra Terbaik 2026 Sudah Resmi di RI  Kam...        Economy
71   Jenius! RTX 3070 Disulap Jadi Pakai VRAM 16GB ...     Technology
72                                      Film apa ini!?        Economy
73   Di COMPUTEX 2026  SK hynix menghadirkan produk...     Technology
74   5G Bukan Lagi Teknologi 'Orang IT'  Kini Dekat...        Economy
75   benar-benar salah satu poster drama terindah y...  Entertainment
76   PERTUMBUHAN 5 6% TAPI RUPIAH & IHSG TERBURUK: ...        Economy
77   Akibat dari rasa frustasi para pengusaha. Tany...        Economy
78   Rencana pemerintah untuk membentuk BUMN Khusus...        Economy
79                          Teh! Eh kok jumlahnya sama        Economy
80   Elon Musk & Komisi Sekuritas AS Diduga Main Ma...        Economy
81   Liburan Panjang  Puas-puasin Movie Marathon Ha...        Economy
82   Guys  Yanuar Rizky memberikan analogi yang men...  Entertainment
83   Syarat Berat Gemini Intelligence: RAM 12GB dan...     Technology
84   Di tengah membanjirnya informasi dan kegelisah...        Economy
85   Bocoran Galaxy Z Fold8 dan Fold Wide: Upgrade ...     Technology
86   Sam Altman Sebut Elon Musk Gila Kontrol  OpenA...     Technology
87   Di media cuman memberitakan perekonomiannya ma...        Economy
88   Ditanya kenapa sih IHSG bisa anjlok  begini si...        Economy
89   Baru tadi pagi digoreng narasi 'Rupiah stabil'...        Economy
90   Di #COMPUTEX2026  @SKhynix memamerkan inovasi ...     Technology
91   Sebelum asal klik link atau download file  cob...        Economy
92   Berantemlah Bennix vs Reinald K  rakyat nonton...        Economy
93   Saya benar-benar tidak dapat mengetahui nama f...  Entertainment
94   Omong kosong belaka videoin biar narik pelangg...        Economy
95   Kayanya Purbaya OJK dan piranti keuangan negar...        Economy
96   Jamin Prediksi Cuaca Makin Akurat di Indonesia...        Economy
97   Viral UFO di Natuna  Mirip Objek Misterius di ...  Entertainment
98              WIT STUDIO DIMASAK DENGAN ANIMASI INI.  Entertainment
99   sudah di singgung  pemerintah gak pingin kita ...        Economy
100                            Dimana untuk menonton??        Economy
101  Perekonomian sedang runtuh. Tidak ada investor...        Economy
102  Read more: Amid the weakening rupiah and IHSG ...  Entertainment
103  Tahun Depan  Indonesia Luncurkan Dua Satelit B...     Technology
104  Aduh! Ini beneran weaponnya phrolo bisa jadi s...        Economy
105                                              Nama?        Economy
106      Prosesor Masa Depan Diprediksi Punya 512 Core     Technology
107  Media internasional kembali menyoroti keadaan ...        Economy
108  Perebutan 'Kue' Internet Satelit RI Memanas  P...     Technology
109  Kalo benar begini berarti ada permainan antar ...     Technology
110  Heboh! Donald Trump Posting Foto Bareng Alien ...     Technology
111      Profesor Ryuk telah menjadi karakter terkuat.  Entertainment
112  Memang benar bahwa segala sesuatunya harus ber...  Entertainment
113       Ini gila! Visualnya benar-benar menakjubkan!        Economy
114          Apa itu dan di mana saya bisa menontonnya  Entertainment
115  Galaxy Z Flip8 Kabarnya Tak Punya Penerus  Jad...     Technology
116  Harga MacBook Neo RI Bikin Kaget  Lebih Murah ...     Technology
117           Tingkat sinkronisasi Oguri sangat tinggi        Economy
118  Apakah kalian siap untuk apa yang akan datang?...        Economy
119                               Visual! .. Animasi..     Technology
120  Bisnis apa yang aman untuk dimulai ketika pere...  Entertainment
121  Masuk Gedung Diminta KTP dan Foto? Ternyata Ad...        Economy
122  Pertama di RI  Fitur Diabetes Risk Study Hadir...     Technology
123  RI Kini Satu Circle dengan Raksasa Prakiraan C...        Economy
124  Microsoft Mau Bangun Data Center  Presiden Ket...     Technology
125  Buat yg ngumpulin coral mungkin di pullnya di ...  Entertainment
126  Saat Anies Baswedan menyebut daya beli masyara...        Economy
127  Spesifikasi Garmin Forerunner 70 dan 170  Buat...     Technology
128  Mulai dari perangkat keras terbaru hingga kola...     Technology
129  Sutradara 'Re:Zero' Masaharu Watanabe baru-bar...        Economy
130  Unboxing MacBook Neo: Laptop Apple Rp 10 Jutaa...     Technology
131  WhatsApp Web Down   Malah Muncul Facebook Biki...     Technology
132  Teroris Rekrut Anak Lewat Chat Game  Ini yang ...  Entertainment
133  Mantan Bos Google Dicemooh Saat Sebut AI di Pi...        Economy
134  bobot adegan ini tidak nyata. Reaksi Sakura da...  Entertainment
135             sayang! cw // spoiler pencarian archon  Entertainment
136       Harga MacBook Neo di RI Mulai Rp 10 749 Juta     Technology
137  Fitur Baru WhatsApp: Bisa Curhat dan Bahas Hal...     Technology
138  Bandar Antariksa Biak Diklaim Lebih Strategis ...        Economy
139  Menteri Keuangan Purbaya Yudhi Sadewa menangga...        Economy
140  Xiaomi 17T Series Dipastikan Rilis Akhir Mei  ...        Economy
141          Intel Kabarnya Mulai Produksi Chip iPhone     Technology
142  Samsung Buka Pendaftaran One UI 9 Beta  Ini HP...     Technology
143  Apple Bocorkan Agenda WWDC 2026   Ada Gebrakan...     Technology
144  Sudah waktunya untuk mengakui bahwa Donghua se...  Entertainment
145  Masahiro Itosugi author di balik seri terkenal...     Technology
146   DJI Pamer Osmo Pocket 4P di Festival Film Cannes  Entertainment
147  Peringatan dari S&P Global menunjukkan betapa ...        Economy
148  Sayangnya  Indonesia memiliki Presiden yang si...        Economy
149  Ini kalau gak bisa rebound sih emang permasala...     Technology
150             Apa yang kami sebut genre karakter ini  Entertainment
151  Apple Ingin Ganti Aluminium iPhone Pro  Pakai ...     Technology
152  Apa judul film ini? Mengapa ada lingkaran Dr. ...  Entertainment
153  Mantan Rekan Kerja Bilang Omongan Sam Altman T...  Entertainment
154  Bisakah kita berbicara tentang seni percikan k...        Economy
155  omong kosong ini benar-benar terlihat puncak b...        Economy
156                 Kudengar musim 3 akan segera hadir     Technology
157  Fundamentalnya masih terlihat kuat  meski rapu...        Economy
158  Seiring dengan perubahan lanskap komputasi yan...     Technology
159  Kritik yang disampaikan sejalan dengan situasi...  Entertainment
160                 Kudengar musim 3 akan segera hadir     Technology
161  Spotify Rilis Party of the Year(s)  Fitur Ala ...  Entertainment
162  Kejutan 50 bps kenaikan suku bunga menandakan ...        Economy
163  663 Saham Anjlok ke Level Terendah IHSG Ditutu...        Economy
164  Saat ini Indonesia sedang mengalami KEJADIAN E...        Economy
165  AI Kamera Sony Xperia 1 VIII Jadi Bahan Meme K...     Technology
166  15 Studio Anime Teratas & Animenya yang Paling...  Entertainment
167  lah gua tuh pengguna "tab" ini. males belanja ...        Economy
168  5 Alasan iPhone 17e Rp 13 Jutaan Layak Dibeli ...     Technology
169  Bandingkan dengan Indonesia: Pertumbuhan kita ...        Economy
170  Selamat pagi warga negara Indonesia. Bangun ti...        Economy
171  Memposting acara secara tidak jelas dan tidak ...  Entertainment
172                              Tolong nama animenya?     Technology
173  IHSG melemah di tengah masih tingginya tekanan...        Economy
174  Kredit bermasalah hanya berkisar 2%  dan permo...        Economy
175  Dan nama sialan itu apakah aku hanya membayang...  Entertainment
176  Bitcoin Senilai Rp 6 4 Miliar Selamat Berkat A...        Economy
177  Baca Juga: Di Tengah Pelemahan Rupiah dan Kore...        Economy
178  Zenitsu menggunakan teknik Hinokami Tanjiro da...  Entertainment
179  Google Ubah Android Jadi 'Agen' AI yang Bisa B...     Technology
180  Apakah acara ini memiliki versi sulih suara ba...  Entertainment
181  The Economist baru saja menulis sesuatu yang j...        Economy
182                          PV Karakter Irene Dirilis  Entertainment
183             Apa yang kami sebut genre karakter ini  Entertainment
184  Banyak yang mengira streaming ilegal lewat Tel...     Technology
185  Oke dikonfirmasi oleh Denia. Arsitek Agung ada...        Economy
186                aku sih soalny ga perlu wp standard  Entertainment
187  Sony Xperia 1 VIII Meluncur  Bawa Desain Baru ...     Technology
188  Pertama Najwa bertanya kepada Prabowo "Bagaima...  Entertainment
189  Baca Juga: Selama 34 Tahun  Dugaan Praktik Und...        Economy
190  Pertumbuhan ekonomi secara luas dianggap dangk...        Economy
191  Data OpenAI Dibobol Hacker  Bagaimana Nasib Pe...        Economy
192                     Di mana kita bisa menonton ini  Entertainment
193                              Gambar terlihat bagus  Entertainment
194               sepertinya mesinnya tidak nyata haha  Entertainment
195  LIHAT FAKTA Video Anies Baswedan tentang Situa...        Economy
196                  Teknik pengecatan kulit terungkap     Technology
197                    dia benar-benar menjadi ibunya.        Economy
198  Melemahnya IHSG menjadi bagian dari dinamika p...        Economy
199                                       Nama Donghua        Economy
200  Belum lagi kenaikan suku bunganya. Saat IHSG s...        Economy
201  Apa Saja 5 Keunggulan Telkomsel 5G Powered by ...     Technology
202  Saat ini perekonomian kita masih tumbuh positi...        Economy
203  Sangkar Ling luar biasa! Donghua lebih unggul ...  Entertainment
204  Teknologi Pelacak Bus Haji Pantau Jemaah Indon...     Technology
205            YOOOO AKU PERASAAN INI ADALAH LING CAGE        Economy
206       Jajaran PlayStation State of Play 2026 bocor     Technology
207  SAP Autonomous Enterprise: Kolaborasi Manusia ...     Technology
208  Sumpah muak bgt liat kelakuan presiden dan kab...        Economy
209  Linknet Garap CCTV Berbasis AI di Kawasan Indu...        Economy
210  Hoax dan Deepfake Jadi Ancaman Baru Ketahanan ...  Entertainment
211  Video musik Dungeon Fighter Online "Pilih Racu...        Economy
212  Indonesia di ambang krisis ekonomi akibat kebi...        Economy
213  global sarat tidak pasti  namun dapat mewujudk...        Economy
214  bagian ini?? halo kuro??? Saya tidak bisa berk...     Technology
215  APINDO optimis tumbuh sampai 5 0.04  yuk sambu...        Economy
216  Fundamental perekonomian Indonesia saat ini ja...        Economy
217                              bukan ini saya.......  Entertainment
218  Video Samsung Tanggapi Gugatan Dua Lipa Senila...        Economy
219  Purbaya Yudhi Sadewa menilai kritik The Econom...        Economy
220  iPhone 16 Pro Max Kirana Larasati Ikut Diving ...     Technology
221  Semua karakter KV dari Kimetsu terinspirasi ol...  Entertainment
222                           Film (serial) jenis apa?  Entertainment
223  Xi Jinping Janjikan 'Karpet Merah' Bagi Raksas...        Economy
224  Sayangnya  Indonesia memiliki Presiden yang si...        Economy
225  TIDAK MUNGKIN DEVS INI MENAMBAHKAN EFEK SUARA ...  Entertainment
226  Digitalisasi UMKM Kian Masif  Koneksi Internet...     Technology
227  disiplin kebijakan fiskal selama lebih dari 2 ...        Economy
228  Tapi saya tidak tahu mengapa Donghua di luar T...        Economy
229  Benar-benar sinematik!  Kualitas animasi Ling ...  Entertainment
230  Narasi bahwa daya beli masyarakat melemah tern...        Economy
231                                yo apakah ini bagus  Entertainment
232  Silakan tonton Fullmetal Alchemist All-Star de...  Entertainment
233  kalian semua apa dialognya jika Anda memilih u...  Entertainment
234  CEO Qualcomm Cristiano Amon berbagi bagaimana ...     Technology
235  âPertumbuhan kuartal I-2026 menembus 5 61%!â...        Economy
236  â Menteri Keuangan (Menkeu) Purbaya Yudhi Sa...        Economy
237  "tgl 10 Juni 2026" "jika dijumlahkan angkanya ...        Economy
238  Saya sangat menentang gagasan ini. Game ini bu...     Technology
239                              Penguasa misteri kan?        Economy
240       Udah diganti sama AI flop kayak gini soalnya  Entertainment
241  Musim apa ini? Kalau saya telusuri season pert...  Entertainment
242  Kata Siapa Minyak Bumi dari Fosil Dino  Ilmuwa...     Technology
243  Jika saat ini 95% orang percaya kinerja pemeri...        Economy
244        Ya tolong jangan tambahkan judul film/acara  Entertainment
245  Mahasiswa RI Juarai Kompetisi Apple  Bongkar P...     Technology
246  Pameran Ekosistem NVIDIA AI Factory MGX di #CO...     Technology
247  Saat Anda berbicara tentang sebuah serial sebu...  Entertainment
248  Sebagai pemula yang lebih mengutamakan karakte...  Entertainment
249  Menteri Keuangan Purbaya langsung terbang ke A...  Entertainment
250  Senjata Laser Makin Menjamur di Timur Tengah  ...        Economy
251  Membantah pengamat yg sarat pesan sponsor yg m...        Economy
252  Ngeri! Dua Jet Tempur Angkatan Laut AS Bertabr...        Economy
253  Menteri Koordinator (Menko) Bidang Perekonomia...        Economy
254  Ramalan Teknologi Zaman Dulu Ini Bikin Tercengang     Technology
255  'Gerbang Internet' di Wamena Bikin Internet Pa...     Technology
256  Dasco datang  IHSG tumbang. Apakah itu dalangn...        Economy
257  yup tidak ada jalan keluarnya  perekonomian in...        Economy
258  Dimana kita bisa nonton anime donghua di websi...  Entertainment
259  Pembacaan situasi perekonomian mengenai bahaya...        Economy
260  Presiden Prabowo Subianto menyoroti global. Me...        Economy
261  â¢ Perekonomian kita buruk â¢ Daya beli menu...        Economy
262                                 Sangkar Ling bagus  Entertainment
263  Kesimpulannya  perekonomian Indonesia belum te...        Economy
264  Ada apa dengan perekonomian Indonesia? Apakah ...  Entertainment
265  Meta Latih AI Pakai Gerak-gerik Karyawan  Biki...     Technology
266           The Boys resmi berakhir setelah 7 tahun.        Economy
267   Show Bangun Platform Film Berbasis Kripto dan AI  Entertainment
268  Siapa yang mengira kalau acara penutupan "Mara...  Entertainment
269                                    Donghua > Anime     Technology
270  doa terbaik untuk perekonomian Indonesia semog...  Entertainment
271  Kondisi Indonesia sangat bagus... Perekonomian...        Economy
272  Cristian Chivu Panen Pujian Usai Bawa Inter Mi...  Entertainment
273  Masa depan yang berorientasi pada agen membutu...     Technology
274                         Saya suka hal semacam ini.  Entertainment
275  Video: NVIDIA Luncurkan Tekonologi Baru Untuk ...        Economy
276  Jadwal MPL ID S17 Week 8: Dewa United Esports ...        Economy
277  Meski Purbaya sering mengklaim semuanya baik-b...     Technology
278  Kondisi perekonomian Indonesia saat ini sangat...  Entertainment
279                      Di mana saya bisa menontonnya  Entertainment
280  Ini bagus buat ngumpulin coral dibanding di se...  Entertainment
281  Jadi  masalahnya bukan hanya apakah perekonomi...        Economy
282  Daftar HP Samsung yang Dukung AirDrop untuk Tr...     Technology
283  Bisakah kita berbicara tentang seni percikan k...        Economy

# Result

In [83]:
print()
# pd.set_option("display.max_rows", None)
# pd.set_option("display.max_columns", None)
# display(df)
df.head()

,Tweet,Category,text_clean,prediction
0,itulah yang saya rasakan tentang The Sandman,Entertaiment,itulah yang saya rasakan tentang the sandman,Entertainment
1,Kompilasi video kecepatan 4x dari sesi gacha 4...,Entertaiment,kompilasi video kecepatan 4x dari sesi gacha 4...,Entertainment
2,Jadwal MPL ID S17 Week 8 Hari Ini: Dewa United...,Technology,jadwal mpl id s17 week 8 hari ini: dewa united...,Economy
3,SALAH SATU PENYEBAB KEMISKINAN BUKAN KARENA KE...,Economy,salah satu penyebab kemiskinan bukan karena ke...,Entertainment
4,bayangkan jika setiap serial animasi meningkat...,Entertaiment,bayangkan jika setiap serial animasi meningkat...,Entertainment

Prediction Distirbution

In [78]:
prediction_summary = (
    df["prediction"]
    .value_counts()
    .sort_index()
    .reset_index()
)

prediction_summary.columns = [
    "Category",
    "Count"
]

display(prediction_summary)

        Category  Count
0        Economy    131
1  Entertainment     90
2     Technology     79

Save Prediction

In [79]:
os.makedirs("results/prediction", exist_ok=True)

MODEL_NAME = CONFIG[SCENARIO]["name"]

OUTPUT = (
    f"results/prediction/"
    f"{MODEL_NAME}_{DATASET_NAME}.csv"
)

df.to_csv(OUTPUT, index=False)

print()
print("Prediction Saved!")

print()
print(OUTPUT)

Prediction Saved!

results/prediction/fasttext_svm_full.csv

Save summary

In [80]:
SUMMARY_OUTPUT = (
    f"results/prediction/"
    f"{MODEL_NAME}_{DATASET_NAME}_summary.csv"
)

prediction_summary.to_csv(SUMMARY_OUTPUT, index=False)

print()
print("Summary Saved!")

print()
print(SUMMARY_OUTPUT)

Summary Saved!

results/prediction/fasttext_svm_full_summary.csv

Experiment Info

In [81]:
print()
print("="*50)
print("PREDICTION FINISHED")
print("="*50)

print()
print("Scenario :")
print(CONFIG[SCENARIO]["name"])

print()
print("Corpus :")
print(DATASET_NAME)

print()
print("Input Data :")
print(len(df))

print()
print("Prediction File :")
print(OUTPUT)

print()
print("Summary File :")
print(SUMMARY_OUTPUT)

print()
print("="*50)

==================================================
PREDICTION FINISHED
==================================================

Scenario :
fasttext_svm

Corpus :
full

Input Data :
300

Prediction File :
results/prediction/fasttext_svm_full.csv

Summary File :
results/prediction/fasttext_svm_full_summary.csv

==================================================