In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('dataset/dataset.csv', sep=',')

In [9]:
df

,No,News Title,Category,News Title Indonesia
0,516,Nest Protect gets a recall and a software update,Technology,Nest Protect mendapat penarikan kembali dan pe...
1,57294,PS4 vs. Xbox One: 6 Months Later,Technology,PS4 vs. Xbox One: 6 Bulan Kemudian
2,46254,Church Roundup,Entertainment,Pertemuan Gereja
3,50315,"Facebook: We have ""no plans"" to redesign Oculu...",Technology,"Facebook: Kami ""tidak punya rencana"" untuk men..."
4,14875,Coup in Thailand spurs cancellations of new bo...,Entertainment,Kudeta di Thailand memicu pembatalan pemesanan...
...,...,...,...,...
48699,60950,Doubts over Garth's Gigs,Entertainment,Keraguan atas Garth's Gigs
48700,42784,Average US 30-year mortgage rate falls to 4.21%,Economy,Rata-rata suku bunga hipotek 30 tahun AS turun...
48701,961,NY at center of fight over food labeling laws,Economy,NY menjadi pusat perebutan undang-undang pelab...
48702,17726,Angelina Jolie perfected her voice for Malefic...,Entertainment,Angelina Jolie menyempurnakan suaranya untuk M...
48703,63265,Officials: Reality TV star Benzino shot by nep...,Entertainment,Pejabat: Bintang reality TV Benzino ditembak o...

In [10]:
df_new = df.drop(columns=['News Title', 'No'])

In [13]:
df_new = df_new.rename(columns={
    'News Title Indonesia': 'tweet',
    'Category': 'category'
})

In [14]:
df_new

            category                                              tweet
0         Technology  Nest Protect mendapat penarikan kembali dan pe...
1         Technology                 PS4 vs. Xbox One: 6 Bulan Kemudian
2      Entertainment                                   Pertemuan Gereja
3         Technology  Facebook: Kami "tidak punya rencana" untuk men...
4      Entertainment  Kudeta di Thailand memicu pembatalan pemesanan...
...              ...                                                ...
48699  Entertainment                         Keraguan atas Garth's Gigs
48700        Economy  Rata-rata suku bunga hipotek 30 tahun AS turun...
48701        Economy  NY menjadi pusat perebutan undang-undang pelab...
48702  Entertainment  Angelina Jolie menyempurnakan suaranya untuk M...
48703  Entertainment  Pejabat: Bintang reality TV Benzino ditembak o...

[48704 rows x 2 columns]

In [ ]:
df_new['twe']